name: Build
on:
  push:
    paths-ignore:
      - ".github/**"
      - "*.md"
    branches: [ master ]
  pull_request:
    paths-ignore:
      - ".github/**"
      - "*.md"
    branches: [ master ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache
        uses: actions/cache@v1.0.0
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Run Tests
        run: .github/workflows/run-tests.sh
